# Generated by Django 4.1.4 on 2022-12-07 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('adresseid', models.AutoField(db_column='AdresseId', primary_key=True, serialize=False)),
                ('adresse1', models.CharField(db_column='Adresse1', max_length=50)),
                ('adresse2', models.CharField(blank=True, db_column='Adresse2', max_length=50, null=True)),
                ('valide', models.IntegerField(db_column='Valide')),
            ],
            options={
                'db_table': 'adresse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, db_column='Nom', max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, db_column='Prenom', max_length=50, null=True)),
                ('qui', models.CharField(blank=True, db_column='Qui', max_length=50, null=True)),
                ('quand', models.DateTimeField(blank=True, db_column='Quand', null=True)),
                ('operation', models.CharField(blank=True, db_column='Operation', max_length=6, null=True)),
            ],
            options={
                'db_table': 'audit_contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contactid', models.AutoField(db_column='ContactId', primary_key=True, serialize=False)),
                ('titre', models.CharField(blank=True, db_column='Titre', max_length=3, null=True)),
                ('nom', models.CharField(db_column='Nom', max_length=50)),
                ('prenom', models.CharField(blank=True, db_column='Prenom', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=150, null=True)),
                ('telephone', models.CharField(blank=True, db_column='Telephone', max_length=15, null=True)),
                ('telecopie', models.CharField(blank=True, db_column='Telecopie', max_length=15, null=True)),
                ('sexe', models.CharField(blank=True, db_column='Sexe', max_length=1, null=True)),
                ('portable', models.CharField(blank=True, db_column='Portable', max_length=15, null=True)),
                ('adressepostaleid', models.IntegerField(blank=True, db_column='AdressePostaleId', null=True)),
            ],
            options={
                'db_table': 'contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField(blank=True, null=True, unique=True)),
                ('joursemaine', models.IntegerField(blank=True, db_column='JourSemaine', null=True)),
            ],
            options={
                'db_table': 'dates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Decideur',
            fields=[
                ('decideurid', models.AutoField(db_column='DecideurId', primary_key=True, serialize=False)),
                ('dateannulation', models.DateField(blank=True, db_column='DateAnnulation', null=True)),
                ('envoisparemail', models.IntegerField(db_column='EnvoisParEmail')),
                ('envoisparcourrier', models.IntegerField(db_column='EnvoisParCourrier')),
            ],
            options={
                'db_table': 'decideur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Elections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parti', models.CharField(blank=True, max_length=5, null=True)),
                ('candidat', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'elections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('employeid', models.IntegerField(db_column='EmployeId', primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='Nom', max_length=50, unique=True)),
                ('chefid', models.IntegerField(blank=True, db_column='ChefId', null=True)),
            ],
            options={
                'db_table': 'employe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('evaluationid', models.AutoField(db_column='EvaluationId', primary_key=True, serialize=False)),
                ('tauxsatisfaction', models.IntegerField(db_column='TauxSatisfaction')),
                ('interet', models.IntegerField(blank=True, db_column='Interet', null=True)),
                ('tempsaccorde', models.IntegerField(blank=True, db_column='TempsAccorde', null=True)),
                ('exercices', models.IntegerField(blank=True, db_column='Exercices', null=True)),
                ('support', models.IntegerField(blank=True, db_column='Support', null=True)),
                ('animation', models.IntegerField(blank=True, db_column='Animation', null=True)),
                ('equilibre', models.IntegerField(blank=True, db_column='Equilibre', null=True)),
                ('observations', models.CharField(blank=True, db_column='Observations', max_length=2048, null=True)),
                ('ajouter', models.CharField(blank=True, db_column='Ajouter', max_length=2048, null=True)),
                ('supprimer', models.CharField(blank=True, db_column='Supprimer', max_length=2048, null=True)),
                ('attentes', models.IntegerField(blank=True, db_column='Attentes', null=True)),
                ('organisation', models.IntegerField(blank=True, db_column='Organisation', null=True)),
                ('accueil', models.IntegerField(blank=True, db_column='Accueil', null=True)),
                ('confort', models.IntegerField(blank=True, db_column='Confort', null=True)),
                ('connaissancepacha', models.IntegerField(blank=True, db_column='ConnaissancePacha', null=True)),
                ('nouveautes', models.IntegerField(blank=True, db_column='Nouveautes', null=True)),
                ('recommandation', models.IntegerField(blank=True, db_column='Recommandation', null=True)),
                ('jour1interet', models.IntegerField(blank=True, db_column='Jour1Interet', null=True)),
                ('jour2interet', models.IntegerField(blank=True, db_column='Jour2Interet', null=True)),
                ('jour3interet', models.IntegerField(blank=True, db_column='Jour3Interet', null=True)),
                ('jour4interet', models.IntegerField(blank=True, db_column='Jour4Interet', null=True)),
                ('jour5interet', models.IntegerField(blank=True, db_column='Jour5Interet', null=True)),
                ('jour1pedagogie', models.IntegerField(blank=True, db_column='Jour1Pedagogie', null=True)),
                ('jour2pedagogie', models.IntegerField(blank=True, db_column='Jour2Pedagogie', null=True)),
                ('jour3pedagogie', models.IntegerField(blank=True, db_column='Jour3Pedagogie', null=True)),
                ('jour4pedagogie', models.IntegerField(blank=True, db_column='Jour4Pedagogie', null=True)),
                ('jour5pedagogie', models.IntegerField(blank=True, db_column='Jour5Pedagogie', null=True)),
                ('formation', models.CharField(blank=True, db_column='Formation', max_length=512, null=True)),
                ('dateevaluation', models.DateTimeField(db_column='DateEvaluation')),
                ('typesaisie', models.IntegerField(blank=True, db_column='TypeSaisie', null=True)),
                ('annulee', models.IntegerField(blank=True, db_column='Annulee', null=True)),
                ('moyenne', models.DecimalField(blank=True, db_column='Moyenne', decimal_places=2, max_digits=4, null=True)),
                ('miseajour', models.IntegerField(db_column='MiseAJour')),
                ('datemiseajour', models.DateTimeField(blank=True, db_column='DateMiseAJour', null=True)),
            ],
            options={
                'db_table': 'evaluation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('facturecd', models.CharField(db_column='FactureCd', max_length=50, primary_key=True, serialize=False)),
                ('coderemise', models.CharField(blank=True, db_column='CodeRemise', max_length=2, null=True)),
                ('remise', models.DecimalField(blank=True, db_column='Remise', decimal_places=7, max_digits=10, null=True)),
                ('datecreation', models.DateTimeField(db_column='DateCreation')),
                ('datefacture', models.DateField(blank=True, db_column='DateFacture', null=True)),
                ('relance', models.PositiveIntegerField(db_column='Relance')),
                ('daterelance', models.DateField(blank=True, db_column='DateRelance', null=True)),
                ('part', models.DecimalField(blank=True, db_column='PART', decimal_places=4, max_digits=7, null=True)),
                ('referencecommande', models.CharField(blank=True, db_column='ReferenceCommande', max_length=100, null=True)),
                ('montantht', models.DecimalField(db_column='MontantHT', decimal_places=2, max_digits=7)),
                ('montantttc', models.DecimalField(db_column='MontantTTC', decimal_places=2, max_digits=7)),
                ('tauxtva', models.DecimalField(db_column='TauxTVA', decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'facture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('formateurid', models.AutoField(db_column='FormateurId', primary_key=True, serialize=False)),
                ('nosecuritesociale', models.CharField(blank=True, db_column='NoSecuriteSociale', max_length=18, null=True)),
                ('statut', models.CharField(blank=True, db_column='Statut', max_length=1, null=True)),
                ('commentaires', models.CharField(blank=True, db_column='Commentaires', max_length=1000, null=True)),
                ('nepascontacter', models.IntegerField(db_column='NePasContacter')),
                ('cv', models.IntegerField(blank=True, db_column='CV', null=True)),
                ('creationdate', models.DateField(db_column='CreationDate')),
                ('creationuser', models.CharField(db_column='CreationUser', max_length=128)),
            ],
            options={
                'db_table': 'formateur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('inscriptionid', models.AutoField(db_column='InscriptionId', primary_key=True, serialize=False)),
                ('sessionid', models.IntegerField(db_column='SessionId')),
                ('dateannulation', models.DateField(blank=True, db_column='DateAnnulation', null=True)),
                ('remise', models.PositiveIntegerField(db_column='Remise')),
                ('present', models.IntegerField(db_column='Present')),
                ('datecreation', models.DateTimeField(db_column='DateCreation')),
                ('referencecommande', models.CharField(blank=True, db_column='ReferenceCommande', max_length=100, null=True)),
                ('conventionenvoyee', models.IntegerField(db_column='ConventionEnvoyee')),
                ('convocationenvoyee', models.IntegerField(db_column='ConvocationEnvoyee')),
                ('listeattente', models.IntegerField(db_column='ListeAttente')),
                ('feuilleemargement', models.CharField(blank=True, db_column='FeuilleEmargement', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'inscription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('languecd', models.CharField(db_column='LangueCd', max_length=2, primary_key=True, serialize=False)),
                ('nomlocal', models.CharField(db_column='NomLocal', max_length=50, unique=True)),
                ('nomfrancais', models.CharField(db_column='NomFrancais', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'langue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lieuformation',
            fields=[
                ('lieuformationid', models.AutoField(db_column='LieuFormationId', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, db_column='Nom', max_length=30, null=True)),
                ('adresse1', models.CharField(blank=True, db_column='Adresse1', max_length=40, null=True)),
                ('adresse2', models.CharField(blank=True, db_column='Adresse2', max_length=40, null=True)),
                ('codepostal', models.CharField(blank=True, db_column='CodePostal', max_length=7, null=True)),
                ('ville', models.CharField(blank=True, db_column='Ville', max_length=20, null=True)),
                ('metro', models.CharField(blank=True, db_column='Metro', max_length=30, null=True)),
                ('telephone', models.CharField(blank=True, db_column='Telephone', max_length=25, null=True)),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=25, null=True)),
                ('planacces', models.CharField(blank=True, db_column='PlanAcces', max_length=255, null=True)),
                ('nomcontact', models.CharField(blank=True, db_column='NomContact', max_length=50, null=True)),
                ('emailcontact', models.CharField(blank=True, db_column='EmailContact', max_length=200, null=True)),
                ('estcentrepacha', models.IntegerField(db_column='EstCentrePacha')),
            ],
            options={
                'db_table': 'lieuformation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modepaiement',
            fields=[
                ('modepaiementcd', models.CharField(db_column='ModePaiementCd', max_length=8, primary_key=True, serialize=False)),
                ('libelle', models.CharField(db_column='Libelle', max_length=64, unique=True)),
            ],
            options={
                'db_table': 'modepaiement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nombre',
            fields=[
                ('nombre', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'nombre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('payscd', models.CharField(db_column='PaysCD', max_length=3, primary_key=True, serialize=False)),
                ('nomfrancais', models.CharField(db_column='NomFrancais', max_length=50, unique=True)),
                ('nomanglais', models.CharField(db_column='NomAnglais', max_length=50)),
                ('code2', models.CharField(db_column='Code2', max_length=2)),
                ('capitale', models.CharField(blank=True, db_column='Capitale', max_length=50, null=True)),
            ],
            options={
                'db_table': 'pays',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('regionid', models.AutoField(db_column='RegionId', primary_key=True, serialize=False)),
                ('typeregion', models.CharField(blank=True, db_column='TypeRegion', max_length=20, null=True)),
                ('coderegion', models.CharField(blank=True, db_column='CodeRegion', max_length=10, null=True)),
                ('nom', models.CharField(db_column='Nom', max_length=50)),
                ('codecheflieu', models.CharField(blank=True, db_column='CodeChefLieu', max_length=3, null=True)),
                ('nomcheflieu', models.CharField(blank=True, db_column='NomChefLieu', max_length=50, null=True)),
                ('xcheflieu', models.SmallIntegerField(blank=True, db_column='XChefLieu', null=True)),
                ('ycheflieu', models.SmallIntegerField(blank=True, db_column='YChefLieu', null=True)),
                ('xcentroide', models.SmallIntegerField(blank=True, db_column='XCentroide', null=True)),
                ('ycentroide', models.SmallIntegerField(blank=True, db_column='YCentroide', null=True)),
                ('codedepartement', models.CharField(blank=True, db_column='CodeDepartement', max_length=2, null=True)),
                ('nomdepartement', models.CharField(blank=True, db_column='NomDepartement', max_length=50, null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salleformation',
            fields=[
                ('salleformationid', models.AutoField(db_column='SalleFormationId', primary_key=True, serialize=False)),
                ('places', models.PositiveIntegerField(db_column='Places')),
                ('nom', models.CharField(blank=True, db_column='Nom', max_length=20, null=True)),
                ('numero', models.CharField(blank=True, db_column='Numero', max_length=3, null=True)),
                ('couloir', models.CharField(blank=True, db_column='Couloir', max_length=1, null=True)),
                ('direction', models.CharField(blank=True, db_column='Direction', max_length=1, null=True)),
                ('etage', models.PositiveIntegerField(blank=True, db_column='Etage', null=True)),
            ],
            options={
                'db_table': 'salleformation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionid', models.AutoField(db_column='SessionId', primary_key=True, serialize=False)),
                ('datedebut', models.DateField(db_column='DateDebut')),
                ('prix', models.DecimalField(blank=True, db_column='Prix', decimal_places=2, max_digits=8, null=True)),
                ('note', models.PositiveIntegerField(blank=True, db_column='Note', null=True)),
                ('statut', models.CharField(blank=True, db_column='Statut', max_length=10, null=True)),
                ('datecreation', models.DateField(db_column='DateCreation')),
                ('duree', models.PositiveIntegerField(blank=True, db_column='Duree', null=True)),
                ('intraentrerprise', models.IntegerField(db_column='IntraEntrerprise')),
                ('remarques', models.CharField(blank=True, db_column='Remarques', max_length=1500, null=True)),
            ],
            options={
                'db_table': 'session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('societeid', models.AutoField(db_column='SocieteId', primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='Nom', max_length=60, unique=True)),
                ('numerotva', models.CharField(blank=True, db_column='NumeroTVA', max_length=30, null=True)),
                ('typerelance', models.SmallIntegerField(db_column='TypeRelance')),
                ('facturationavantinscription', models.IntegerField(db_column='FacturationAvantInscription')),
                ('telephone2', models.CharField(blank=True, db_column='Telephone2', max_length=30, null=True)),
                ('telephone1', models.CharField(blank=True, db_column='Telephone1', max_length=30, null=True)),
                ('remise', models.PositiveIntegerField(db_column='Remise')),
            ],
            options={
                'db_table': 'societe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Societeformateur',
            fields=[
                ('societeformateurid', models.AutoField(db_column='SocieteFormateurId', primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='Nom', max_length=50, unique=True)),
                ('telephonesociete', models.CharField(blank=True, db_column='TelephoneSociete', max_length=30, null=True)),
                ('telephoneadministratif', models.CharField(blank=True, db_column='TelephoneAdministratif', max_length=30, null=True)),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=30, null=True)),
                ('contact', models.CharField(blank=True, db_column='Contact', max_length=150, null=True)),
                ('commentaires', models.CharField(blank=True, db_column='Commentaires', max_length=1000, null=True)),
                ('statut', models.CharField(blank=True, db_column='Statut', max_length=1, null=True)),
                ('emailcontact', models.CharField(blank=True, db_column='EmailContact', max_length=150, null=True)),
            ],
            options={
                'db_table': 'societeformateur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('stageid', models.AutoField(db_column='StageId', primary_key=True, serialize=False)),
                ('categorie', models.CharField(db_column='Categorie', max_length=2)),
                ('domaine', models.CharField(db_column='Domaine', max_length=2)),
                ('datecreation', models.DateTimeField(db_column='DateCreation')),
                ('dateannulation', models.DateField(blank=True, db_column='DateAnnulation', null=True)),
                ('commentairesplanification', models.CharField(blank=True, db_column='CommentairesPlanification', max_length=2000, null=True)),
                ('commentairesproduction', models.CharField(blank=True, db_column='CommentairesProduction', max_length=2000, null=True)),
                ('duree', models.PositiveIntegerField(db_column='Duree')),
                ('nombrestagiairesmaximum', models.PositiveIntegerField(db_column='NombreStagiairesMaximum')),
            ],
            options={
                'db_table': 'stage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suivifacture',
            fields=[
                ('suivifactureid', models.AutoField(db_column='SuiviFactureId', primary_key=True, serialize=False)),
                ('datepaiement', models.DateField(db_column='DatePaiement')),
                ('typepaiement', models.CharField(db_column='TypePaiement', max_length=1)),
                ('nochequebanque', models.CharField(blank=True, db_column='NoChequeBanque', max_length=50, null=True)),
                ('nobordereau', models.CharField(blank=True, db_column='NoBordereau', max_length=10, null=True)),
                ('montant', models.DecimalField(db_column='Montant', decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'suivifacture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarifformateur',
            fields=[
                ('tarifformateurid', models.AutoField(db_column='TarifFormateurId', primary_key=True, serialize=False)),
                ('datedebut', models.DateField(db_column='DateDebut')),
                ('datefin', models.DateField(blank=True, db_column='DateFin', null=True)),
                ('tarifjournalier', models.DecimalField(db_column='TarifJournalier', decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'tarifformateur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarifspecial',
            fields=[
                ('tarifspecialid', models.AutoField(db_column='TarifSpecialId', primary_key=True, serialize=False)),
                ('regionid', models.PositiveIntegerField(blank=True, db_column='RegionId', null=True)),
                ('stageid', models.IntegerField(blank=True, db_column='StageId', null=True)),
                ('languecd', models.CharField(blank=True, db_column='LangueCd', max_length=2, null=True)),
                ('tarifjournalier', models.DecimalField(db_column='TarifJournalier', decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'tarifspecial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tauxtva',
            fields=[
                ('datedebut', models.DateField(db_column='DateDebut', primary_key=True, serialize=False)),
                ('datefin', models.DateField(blank=True, db_column='DateFin', null=True)),
                ('taux1', models.DecimalField(db_column='TAUX1', decimal_places=2, max_digits=5)),
                ('taux2', models.DecimalField(blank=True, db_column='TAUX2', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'tauxtva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titre',
            fields=[
                ('titrecd', models.CharField(db_column='TitreCd', max_length=8, primary_key=True, serialize=False)),
                ('libelle', models.CharField(db_column='Libelle', max_length=32, unique=True)),
            ],
            options={
                'db_table': 'titre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Typeadresse',
            fields=[
                ('typeadresseid', models.PositiveIntegerField(db_column='TypeAdresseId', primary_key=True, serialize=False)),
                ('libelle', models.CharField(db_column='Libelle', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'typeadresse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('villeid', models.AutoField(db_column='VilleId', primary_key=True, serialize=False)),
                ('regionid', models.IntegerField(blank=True, db_column='RegionId', null=True)),
                ('nomville', models.CharField(blank=True, db_column='NomVille', max_length=255, null=True)),
                ('codepostal', models.CharField(blank=True, db_column='CodePostal', max_length=10, null=True)),
                ('codeinsee', models.FloatField(blank=True, db_column='CodeINSEE', null=True)),
                ('coderegion', models.FloatField(blank=True, db_column='CodeRegion', null=True)),
                ('latitude', models.DecimalField(blank=True, db_column='Latitude', decimal_places=2, max_digits=6, null=True)),
                ('longitude', models.CharField(blank=True, db_column='Longitude', max_length=255, null=True)),
                ('eloignement', models.CharField(blank=True, db_column='Eloignement', max_length=255, null=True)),
            ],
            options={
                'db_table': 'ville',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Adressesurinscription',
            fields=[
                ('inscriptionid', models.OneToOneField(db_column='InscriptionId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='contacts.inscription')),
                ('facturation', models.IntegerField(db_column='Facturation')),
                ('convention', models.IntegerField(db_column='Convention')),
                ('lettreconvention', models.IntegerField(db_column='LettreConvention')),
                ('attestation', models.IntegerField(db_column='Attestation')),
                ('copie', models.IntegerField(db_column='Copie')),
            ],
            options={
                'db_table': 'adressesurinscription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inscriptionfacture',
            fields=[
                ('inscriptionid', models.OneToOneField(db_column='InscriptionId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='contacts.inscription')),
            ],
            options={
                'db_table': 'inscriptionfacture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Societeadresse',
            fields=[
                ('societeid', models.OneToOneField(db_column='SocieteId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='contacts.societe')),
                ('typeadresse', models.CharField(db_column='TypeAdresse', max_length=1)),
            ],
            options={
                'db_table': 'societeadresse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stagelangue',
            fields=[
                ('stageid', models.OneToOneField(db_column='StageId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='contacts.stage')),
                ('titre', models.CharField(db_column='Titre', max_length=200)),
                ('soustitre', models.CharField(blank=True, db_column='SousTitre', max_length=200, null=True)),
                ('phrasesynthese', models.CharField(blank=True, db_column='PhraseSynthese', max_length=500, null=True)),
                ('prerequis', models.CharField(blank=True, db_column='PreRequis', max_length=1000, null=True)),
                ('profilparticipants', models.CharField(blank=True, db_column='ProfilParticipants', max_length=500, null=True)),
                ('objectifs', models.CharField(blank=True, db_column='Objectifs', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'stagelangue',
                'managed': False,
            },
        ),
    ]
